# Data Science and Programming
# Week 3b

* [Introduction](#Introduction)
 - [Problem](#Problem)
 - [Importing libraries and data](#Importing-libraries-and-data)
 - [Checkpoint 1](#Checkpoint-1)
* [Pre-processing the data](#Pre-processing-the-data)
 - [Removing characters and converting to a string](#Removing-characters-and-converting-to-a-string)
 - [Creating a derived feature](#Creating-a-derived-feature)
 - [Checkpoint 2](#Checkpoint-2)
* [Exploring the data](#Exploring-the-data)
 - [Creating grouped box plots](#Creating-grouped-box-plots)
 - [Finding grouped statistics](#Finding-grouped-statistics)
* [Communicating the results](#Communicating-the-results)
 - [Checkpoint 3](#Checkpoint-3)

 
# Introduction

This activity show you how to clean data, create derived features and group the data for analysis.

The activity uses the data from the OCR large data set which gives the methods of travel to work arranged by English and Welsh local authorities for 2001 and 2011.

## Problem
***Are people more likely to cycle to work or drive to work in different parts of the country?***

To answer this question you could compare the means and standard deviations of the number of people driving and cycling to work for different regions.

## Importing libraries and data
Initially the data for 2011 will be imported.
> Run the code in the boxes below to import the libraries and the 2011 data.

In [1]:
# import pandas for data analysis
import pandas as pd 

# import seaborn for visualisations
import seaborn as sns

In [2]:
# importing the data
travel_2011_data = pd.read_csv('OCR-lds-travel-2011.csv')

# inspecting the dataset to check that it has imported correctly
travel_2011_data

,geography code,Region,LA,In employment,Work at home,"Underground, tram",Train,Bus,Taxi,Motorcycle,Driving a car,Passenger in a car,Bicycle,On foot,Other,Not in employment
0,E06000047,North East,County Durham,"227,894","20,652",323,"1,865","13,732","1,401","1,038","146,644","17,362","2,205","21,490","1,182","155,902"
1,E06000005,North East,Darlington,"49,014","4,180",33,828,"3,380",403,191,"28,981","3,337","1,151","6,284",246,"27,621"
2,E08000020,North East,Gateshead,"91,877","6,383","4,270",705,"13,909",453,364,"50,236","5,830","1,314","7,966",447,"56,202"
3,E06000001,North East,Hartlepool,"37,767","2,473",33,469,"2,556",673,175,"22,863","3,157",706,"4,305",357,"29,037"
4,E06000002,North East,Middlesbrough,"54,547","3,337",44,698,"4,868",902,195,"31,155","4,639","1,375","6,769",565,"46,004"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,W06000016,Wales,"Rhondda, Cynon, Taff","99,327","6,778",61,"4,114","3,932",217,445,"67,154","7,995",441,"7,836",354,"72,720"
344,W06000011,Wales,Swansea,"102,793","8,228",100,883,"5,791",636,610,"66,912","7,585","1,485","9,997",566,"74,178"
345,W06000014,Wales,The Vale of Glamorgan,"58,978","5,886",83,"3,450","1,681",251,328,"38,079","3,177",998,"4,701",344,"32,838"
346,W06000020,Wales,Torfaen,"40,261","2,582",30,475,"1,892",308,301,"28,057","3,074",326,"3,089",127,"25,846"
347,W06000006,Wales,Wrexham,"63,614","5,324",37,496,"3,361",424,397,"42,179","5,187",808,"5,128",273,"35,077"

This data has imported all the numerical features with the comma separators for thousands. This is problematic as they will be interpreted as text features (or "strings") and therefore it will not be possible to calculate statistics such as the mean or the standard deviation. 

> Use the `info()` command you learnt in lesson 1 to explore the data types

*Reminder: the format for this command in lesson 2 was* `weather_data.info()`

In [ ]:
# explore the data types

## Checkpoint 1
> * You should see that the data type for all features is `object` but looking at the data shows that some fields have numerical values. Give a reason why the numerical features are not showing as `int64` or `float64`. *Hint: look at the characters in the entries.*

# Pre-processing the data
The `In employment` feature has been imported as an `object`. This means that Pandas will treat it like a text feature (or *string*). You can see the effect of this if you use `.describe()` on the feature.

> Run the code below to attempt to find the statistics for `In employment`.

In [ ]:
travel_2011_data['In employment'].describe()

## Removing characters and converting to a string
The values as they are stored have two problems that need to be addressed:
* The strings contain commas for some of the values to separate thousands
* They are being stored as strings and not numbers

These two issues need to be corrected in order. The code below addresses both problems in a single line: 

* To remove the commas you can use the string replace command `.str.replace` to replace any commas with an empty string.
* To then change it to a number you can use `.astype('int')` so pandas will interpret it as an integer.

> Run the code below to create a new feature (`In employment value`) that has the `In employment` data formatted as numbers.

In [ ]:
# any commas in the In employment features are removed by replacing them with an empty string
travel_2011_data['In employment value'] = travel_2011_data['In employment'].str.replace(',', '').astype('int')

# check the data set
travel_2011_data

You can then use the describe command to check that this has worked and the data can now be analysed.

> Run the code below to find the statistics for `In employment value`.

In [ ]:
# find the statistics with describe
travel_2011_data['In employment value'].describe()

The code in the two boxes below repeats this pre-processing for the Bicycle feature.

> Run the code to remove the commas and reformat `Bicycle` as numeric.
>
> Then, copy the code into the following boxes and change it so that it does the same for the `Driving in a car` feature.

In [ ]:
# any commas in the Bicycle feature are removed by replacing them with an empty string and then converting to the int type
travel_2011_data['Bicycle value'] = travel_2011_data['Bicycle'].str.replace(',', '').astype('int')

# display the data to check
travel_2011_data

In [ ]:
# find the statistics with describe
travel_2011_data['Bicycle value'].describe()

In [ ]:
# any commas in the Driving a car feature are removed by replacing them with an empty string and then converting to the int type


# display the data to check

In [ ]:
# find the statistics with describe

## Creating a derived feature
The data in this dataset show the numbers of people in each local authority that use each type of transport as their primary means of getting to work. However, this doesn't take into account the size of the local authority: local authorities with more people living in them will generally have greater numbers across all the categories. To aid comparison between different sized local authorities it is useful to consider the proportion of people who work in each local authority that use each type of transport (expressed as a percentage).

The proportion of people who cycle is a *derived feature*: it is not part of the original dataset but it can be derived from other values, in this case the number who cycle divided by the total number of people in work.

> Run the code in the two boxes below to add the Bicycle percent feature and check that it has added correctly to the data set.

In [ ]:
# The percentage is calculated and stored in a new feature: Bicycle percent
travel_2011_data['Bicycle percent']=travel_2011_data['Bicycle value']/travel_2011_data['In employment value']*100

# display the data
travel_2011_data

> Copy the code into the following box and change it so that it adds a column for `Driving a car percent`.

In [ ]:
# The percentage is calculated and stored in a new feature: Driving a car percent


# display the data

## Checkpoint 2
> When would you use the raw number of people using a type of transport and when would you use a percentage?

# Exploring the data
## Creating grouped box plots 

It is useful to see the boxplots for these features. The code in the two boxes below will generate the boxplots grouped by region. Plotting charts will be explored in more detail in lesson 3.

> Run the code below to create the box plots

In [ ]:
# plot a boxplot for Bicycle percent grouped by Region
sns.catplot(data=travel_2011_data, kind='box', x='Bicycle percent', y='Region', aspect=3);

> Copy the code into the following box and change it so that it creates the box plots for the `Driving a car percent` feature.

In [ ]:
# plot a boxplot for Driving a car percent grouped by Region

## Finding grouped statistics
The data in this dataset is listed by local authority and region. Pandas contains a built-in command: `groupby` that allows for operations to be performed on different groups.

> Run the code below which calculates the statistics for the data grouped by region

In [ ]:
# Calculate the grouped statistics 
travel_2011_data.groupby('Region')['Bicycle percent'].describe()

> Copy the code into the following box and change it so that it calculates the statistics for the `Driving a car percent` feature

In [ ]:
# Calculate the grouped statistics

# Communicating the results
Use the measures calculated to answer the orginal problem: 

***Are people more likely to cycle to work or drive to work in different parts of the country?***
## Checkpoint 3
> * Which regions have the highest/lowest proportion of people cycling or driving to work? Which regions have the most variation?
> * What local factors might affect the proportion of people cycling or driving to work? For example the geography, types of people who live there or other factors.